
import busqueda_binaria.BusquedaBinaria;
import busqueda_binaria.MetodosInternos;
import busqueda_secuencia.BusquedaSecuencial;
import busqueda_hash.Hash;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jose
 */
public class Ventana extends javax.swing.JFrame {

    int n;
    Hash objHash;
    int arreglo[];
    busqueda_binaria.BusquedaBinaria binaria;
    busqueda_secuencia.BusquedaSecuencial secuencial;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();

        btnBinaria.setEnabled(false);
        btnSecuencial.setEnabled(false);
        btnHash.setEnabled(false);
        setLocationRelativeTo(null);
        setTitle("EDD U6 - ALGORITMOS DE BUSQUEDA");

        n = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(this, "Ingrese el tamaño de N "));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        btnBinaria = new javax.swing.JButton();
        btnSecuencial = new javax.swing.JButton();
        btnHash = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        txtSecuencial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBinaria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHash = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Raavi", 1, 18)); // NOI18N
        jLabel1.setText("METODOS DE BUSQUEDA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jLabel2.setText("Dato a buscar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        getContentPane().add(txtDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 60, -1));

        btnBinaria.setText("Binaria");
        btnBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinariaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        btnSecuencial.setText("Secuencial");
        btnSecuencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecuencialActionPerformed(evt);
            }
        });
        getContentPane().add(btnSecuencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        btnHash.setText("Hash");
        btnHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHashActionPerformed(evt);
            }
        });
        getContentPane().add(btnHash, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jLabel3.setText("Tipos de busqueda:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, 100));

        jLabel4.setText("Valores existentes:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        btnGenerar.setText("Generar numeros");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel5.setText("Minimo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));
        getContentPane().add(txtMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 130, -1));

        jLabel6.setText("Maximo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));
        getContentPane().add(txtMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 130, -1));

        txtSecuencial.setEditable(false);
        getContentPane().add(txtSecuencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 130, -1));

        jLabel8.setText("Secuencial");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, 20));

        jLabel9.setText("Binaria");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, 20));

        txtBinaria.setEditable(false);
        getContentPane().add(txtBinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 130, -1));

        jLabel10.setText("Hash");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 20));

        txtHash.setEditable(false);
        getContentPane().add(txtHash, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        arreglo = new int[n];
        String auxS = "";
        int min = Integer.parseInt(txtMin.getText().trim());
        int max = Integer.parseInt(txtMax.getText().trim());
        if (min > max) {
            JOptionPane.showMessageDialog(this, "EL VALOR MINIMO DEBE SER MENOR AL MAXIMO");
            return;
        }
        for (int i = 0; i < n; i++) {
            arreglo[i] = (int) (Math.random() * (max - min) + min);
        }

        arreglo = new MetodosInternos(arreglo).Quicksort();
        for (int i : arreglo) {
            auxS += String.valueOf(i) + ",";
        }
        auxS = auxS.substring(0, auxS.length() - 1);
        btnBinaria.setEnabled(true);
        btnSecuencial.setEnabled(true);
        btnHash.setEnabled(true);
        jTextArea1.setText(auxS);
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinariaActionPerformed
        long total = System.currentTimeMillis();
        binaria = new BusquedaBinaria(arreglo);
        total = System.currentTimeMillis() - total;
        int res = binaria.busqueda(Integer.parseInt(txtDato.getText().trim()));
        if (res == -1) {
            txtBinaria.setText(total + " MILISEGUNDOS");
            JOptionPane.showMessageDialog(this, "VALOR NO ENCONTRADO");
            
            return;
        }
        txtBinaria.setText(total + " MILISEGUNDOS");
        JOptionPane.showMessageDialog(this, "VALOR ENCONTRADO EN LA POSICION " + (res+1));
        
    }//GEN-LAST:event_btnBinariaActionPerformed

    private void btnSecuencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecuencialActionPerformed
        long total = System.currentTimeMillis();
        secuencial = new BusquedaSecuencial(arreglo);
        total = System.currentTimeMillis() - total;
        int res = secuencial.busquedaArreglo(Integer.parseInt(txtDato.getText().trim()));
        if (res == -1) {
            txtSecuencial.setText(total + " MILISEGUNDOS");
            javax.swing.JOptionPane.showMessageDialog(this, "VALOR NO ENCONTRADO");
            
            return;
        }
        txtSecuencial.setText(total + " MILISEGUNDOS");
        JOptionPane.showMessageDialog(this, "VALOR ENCONTRADO EN LA POSICION " + (res+1));
        
    }//GEN-LAST:event_btnSecuencialActionPerformed


    private void btnHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHashActionPerformed
        long total = System.currentTimeMillis();
        int aux = Integer.parseInt(txtDato.getText());
        int hashCode;
        objHash = new Hash(arreglo);
        hashCode = objHash.hashBuscar(aux);
        total = System.currentTimeMillis() - total;
        if (hashCode == -1) {
            txtHash.setText(total + " MILISEGUNDOS");
            javax.swing.JOptionPane.showMessageDialog(this, "No existe");
            return;
        }

        if (arreglo[hashCode] == aux) {
            txtHash.setText(total + " MILISEGUNDOS");
            javax.swing.JOptionPane.showMessageDialog(this, "ENCONTRADO EN LA POSICION " + (hashCode+1));
        }


    }//GEN-LAST:event_btnHashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBinaria;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnHash;
    private javax.swing.JButton btnSecuencial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtBinaria;
    private javax.swing.JTextField txtDato;
    private javax.swing.JTextField txtHash;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtSecuencial;
    // End of variables declaration//GEN-END:variables
}
